---
title: "santa_ynez_hydrology"
author: "Jessica Jagdeo"
date: "11/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include = FALSE}

# Load in necessary packages

library(tidyverse)
library(readxl)
library(janitor)
library(kableExtra)

```

```{r, output = FALSE}

# Read in the hydrology data from USGS flow gauges

flow_gauge_stations <- read_excel("FlowGauge_stations.xlsx")

santa_ynez_los_laurls <- read_excel("SantaYnezLosLaurls_11123500.xlsx") %>% 
  clean_names()

santa_cruz_santa_ynez <- read_excel("SantaCruzSantaYnez_11124500.xlsx") %>% 
  clean_names()

santa_ynez_solvang <- read_excel("SantaYnezSolvang_11128500.xlsx") %>% 
  clean_names()

alamo_pintado <- read_excel("AlamoPintado_11128250.xlsx") %>% 
  clean_names()

zaca_buellton <- read_excel("ZacaBuellton_11129800.xlsx") %>% 
  clean_names()

```

```{r}

# Calculate the summary statistics for each hydrological station

syll_summary <- santa_ynez_los_laurls %>% 
  summarize(
  "Average Flow (cumecs)" = round(mean(discharge_m3_s), 2),
    "Min. Flow (cumecs)" = min(discharge_m3_s),
  "Max Flow (cumecs)" = round(max(discharge_m3_s), 2)
)
syll_summary


scsy_summary <- santa_cruz_santa_ynez %>% 
   summarize(
  "Average Flow (cumecs)" = round(mean(discharge_m3_s), 2),
    "Min. Flow (cumecs)" = min(discharge_m3_s),
  "Max Flow (cumecs)" = round(max(discharge_m3_s), 2)
)
scsy_summary


sys_summary <- santa_ynez_solvang %>% 
   summarize(
  "Average Flow (cumecs)" = round(mean(discharge_m3_s), 2),
    "Min. Flow (cumecs)" = min(discharge_m3_s),
  "Max Flow (cumecs)" = round(max(discharge_m3_s), 2)
)
sys_summary


ap_summary <- alamo_pintado %>% 
   summarize(
  "Average Flow (cumecs)" = round(mean(discharge_m3_s), 2),
    "Min. Flow (cumecs)" = min(discharge_m3_s),
  "Max Flow (cumecs)" = round(max(discharge_m3_s), 2)
)
ap_summary

zb_summary <- zaca_buellton %>% 
   summarize(
  "Average Flow (cumecs)" = round(mean(discharge_m3_s), 2),
    "Min. Flow (cumecs)" = min(discharge_m3_s),
  "Max Flow (cumecs)" = round(max(discharge_m3_s), 2)
)
zb_summary

```

```{r}

# Create a dataframe with the summary statistics for all 5 hydrological stations in the watershed

hydrological_stations <- c("SANTA YNEZ R BL LOS LAURLS CYN NR SNTA YNEZ CA",
                           "SANTA CRUZ C NR SANTA YNEZ CA", 
                           "SANTA YNEZ R A SOLVANG CA", 
                           "ALAMO PINTADO C NR SOLVANG CA", 
                           "ZACA C NR BUELLTON CA" )

hydrological_summary <- rbind(syll_summary, scsy_summary, sys_summary, ap_summary, zb_summary) %>% 
  mutate(Site = hydrological_stations) %>% 
  select(Site, "Average Flow (cumecs)", "Min. Flow (cumecs)", "Max Flow (cumecs)") %>% kable() %>% 
   kable_styling(bootstrap_options = c("striped", "hover"))

hydrological_summary


```

```{r}

# Create a table with information about the hydrological stations

flow_gauge_table <- flow_gauge_stations %>% 
  kable() %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

flow_gauge_table

```

Graphs.
Create hydrographs for each station. Will need to add in the meterological stations later.

```{r}

# Santa Ynez Los Laureles

santa_ynez_los_laurls$date <- as.Date(santa_ynez_los_laurls$date)

syll_graph <- ggplot(santa_ynez_los_laurls, aes(x = date, y = discharge_m3_s)) +
  #geom_point(color = "darkblue") +
  geom_line(color = "darkblue") +
  theme_minimal() +
  scale_x_date(date_labels = "%Y %b %d") +
  labs(x = "Date",
       y = "Flow rate (cumecs)") +
  ggtitle("Santa Ynez Los Laureles (11123500) Flow Station")

syll_graph

```

```{r}

# Santa Cruz Santa Ynez

santa_cruz_santa_ynez$date <- as.Date(santa_cruz_santa_ynez$date)

scsy_graph <- ggplot(santa_cruz_santa_ynez, aes(x = date, y = discharge_m3_s)) +
  #geom_point(color = "darkblue") +
  geom_line(color = "darkblue") +
  theme_minimal() +
  scale_x_date(date_labels = "%Y %b %d") +
  labs(x = "Date",
       y = "Flow rate (cumecs)") +
  ggtitle("Santa Cruz Santa Ynez (11124500) Flow Station")

scsy_graph

```

```{r}

# Santa Ynez Solvang

santa_ynez_solvang$date <- as.Date(santa_ynez_solvang$date)

sys_graph <- ggplot(santa_ynez_solvang, aes(x = date, y = discharge_m3_s)) +
  #geom_point(color = "darkblue") +
  geom_line(color = "darkblue") +
  theme_minimal() +
  scale_x_date(date_labels = "%Y %b %d") +
  labs(x = "Date",
       y = "Flow rate (cumecs)") +
  ggtitle("Santa Ynez Solvang (11128500) Flow Station")

sys_graph

```

```{r}

# Alamo Pintado

alamo_pintado$date <- as.Date(alamo_pintado$date)

ap_graph <- ggplot(alamo_pintado, aes(x = date, y = discharge_m3_s)) +
  #geom_point(color = "darkblue") +
  geom_line(color = "darkblue") +
  theme_minimal() +
  scale_x_date(date_labels = "%Y %b %d") +
  labs(x = "Date",
       y = "Flow rate (cumecs)") +
  ggtitle("Alamo Pintado (11128250) Flow Station")

ap_graph

```

```{r}

# Zaca Buellton

zaca_buellton$date <- as.Date(zaca_buellton$date)

zb_graph <- ggplot(zaca_buellton, aes(x = date, y = discharge_m3_s)) +
  #geom_point(color = "darkblue") +
  geom_line(color = "darkblue") +
  theme_minimal() +
  scale_x_date(date_labels = "%Y %b %d") +
  labs(x = "Date",
       y = "Flow rate (cumecs)") +
  ggtitle("Zaca Buellton (11129800) Flow Station")

zb_graph

```

